CREATE TABLE IF NOT EXISTS `news` (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    title VARCHAR(191) NOT NULL,
    description TEXT,
    image_url VARCHAR(191),
    is_home TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `categories` (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    title VARCHAR(191) NOT NULL UNIQUE,
    slug VARCHAR(191) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `menu` (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    title VARCHAR(191) NOT NULL,
    price DECIMAL(8,2) DEFAULT 0.0,
    description TEXT,
    image_url VARCHAR(191),
    display_status VARCHAR(1) DEFAULT 'N',
    category_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS `events` (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    title VARCHAR(191) NOT NULL,
    description TEXT,
    image_url VARCHAR(191),
    open_date DATE,
    location VARCHAR(191),
    display_status VARCHAR(1) DEFAULT 'N',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `users` (
   id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
   username VARCHAR(191) NOT NULL UNIQUE,
   email VARCHAR(191) NOT NULL UNIQUE,
   password VARCHAR(191),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
)